@ -0,0 +1,31 @@
[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.teams.microsoft.com https://*.login.microsoftonline.com https://*.sharepoint.com https://token.botframework.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.teams.microsoft.com; style-src 'self' 'unsafe-inline' https://*.teams.microsoft.com; img-src 'self' data: https://*.teams.microsoft.com; connect-src 'self' https://*.teams.microsoft.com https://*.login.microsoftonline.com https://*.sharepoint.com https://token.botframework.com;" 